# Stage 1: Build Vite app
FROM node:20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build
RUN npm install

# Stage 2: Serve the build using nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD echo "Frontend available at http://localhost:5173" && nginx -g "daemon off;"


